### ISSUE TITLE
**AssertionError: Got 2022 rows for daily bars table with first day=2010-01-04, last day=2017-12-29, expected 2013 rows.**

### ISSUE THREAD

**Issue by P4k0p4N** [hhatefi/zipline_bundles#1]
getting the folling errors when ingesting iex. Any idea what to do?:

(zipline) pacopan@Franciscos-Mac-mini ~ % zipline ingest -b iex
[2021-01-24 18:00:50.871338] INFO: zipline.data.bundles.core: Ingesting iex.
[2021-01-24 18:00:50.871543] INFO: zipline.data.bundles.ingester: symbols are: ('DBC', 'SPY', 'IEF', 'GLD', 'TLT')
[2021-01-24 18:00:50.872490] INFO: zipline.data.bundles.ingester: writing data...

Traceback (most recent call last):
  File "/Users/pacopan/anaconda3/envs/zipline/bin/zipline", line 33, in <module>
    sys.exit(load_entry_point('zipline==1.4.0', 'console_scripts', 'zipline')())
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/zipline/__main__.py", line 389, in ingest
    show_progress,
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/zipline/data/bundles/core.py", line 443, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/zipline/data/bundles/ingester.py", line 412, in __call__
    daily_bar_writer.write(self._read_and_convert(calendar, show_progress), show_progress=show_progress)
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/zipline/data/bcolz_daily_bars.py", line 207, in write
    return self._write_internal(it, assets)
  File "/Users/pacopan/anaconda3/envs/zipline/lib/python3.6/site-packages/zipline/data/bcolz_daily_bars.py", line 328, in _write_internal
    ).difference(asset_sessions).tolist(),
**AssertionError: Got 2022 rows for daily bars table with first day=2010-01-04, last day=2017-12-29, expected 2013 rows.**
Missing sessions: []
Extra sessions: [Timestamp('2010-01-18 00:00:00+0000', tz='UTC'), Timestamp('2011-04-22 00:00:00+0000', tz='UTC'), Timestamp('2012-10-30 00:00:00+0000', tz='UTC'), Timestamp('2013-01-21 00:00:00+0000', tz='UTC'), Timestamp('2013-02-18 00:00:00+0000', tz='UTC'), Timestamp('2013-03-29 00:00:00+0000', tz='UTC'), Timestamp('2013-07-04 00:00:00+0000', tz='UTC'), Timestamp('2014-09-01 00:00:00+0000', tz='UTC'), Timestamp('2014-11-27 00:00:00+0000', tz='UTC')]

**Comment by hhatefi** [comment]
Hi 

The problem is that iex provides data for days that zipline considers them as holidays.
One way is to change the trading calendar such that these days are considered normal trading days. The other way is to filter those days after fetching and do not pass them into zipline.

Which zipline version are you using?

**Comment by P4k0p4N** [comment]
Thank you 
My Zipline version is 1.40
The iex bundle you created used NYSE calendar.

**Comment by P4k0p4N** [comment]
I checked and all these days were actual holidays of NYSE. Hoe could it be that iex is proving data for them? Is there a way of pre-filter those before ingesting on the ingested or on extensions.py?

Thanks

**Comment by hhatefi** [comment]
Hi

I pushed a new change. I have added a new parameter `filter_cb` to `direct_ingester`. It is a callback that is called when the downloader fetches the data frame. You can add something like

``` python
register('yahoo_direct', # bundle's name                                                                  
         direct_ingester('YAHOO',                                                                         
                         every_min_bar=False,                                                             
                         symbol_list_env='YAHOO_SYM_LST', # the environemnt variable holding the comma se\
parated list of assert names                                                                              
                         downloader=yahoo.get_downloader(start_date='2010-01-05',                         
                                                         end_date='2010-01-08'                            
                         ),                                                                               
                         filter_cb=lambda df: df[df.index != pd.Timestamp('2010-01-06')]                  
         ),                                                                                               
         calendar_name='NYSE',                                                                            
) 
```
to filter date 2010-01-06 out.

I hope this can help you.

**Comment by hhatefi** [comment]
Hi

I [updated](https://github.com/hhatefi/zipline_bundles/commit/72defd7cca303cc061d8796888b16e2750485434) `extension.py` to apply a filter on IEX according to NYSE calendar. Can you please check to see if the problem is solved?

Thanks

**Comment by P4k0p4N** [comment]
Works perfect now! 
Just ingested 10 years of data from iex. 
Thank you!
